### PR TITLE
This is super dope

### PR DESCRIPTION
**Pull request by raphink**
As per https://twitter.com/kelseyhightower/status/804819512608493569

### CODE REVIEW

**Review by josegonzalez — APPROVED** [review]

**Comment by kelseyhightower** [comment]
LGTM

**Comment by mikecb** [comment]
Noooooo!

**Comment by josegonzalez** [comment]
@kelseyhightower https://cl.ly/1r0Q0d0A2n3D

**Review by mikecb — APPROVED** [review]

**Comment by ghost** [comment]
This is awesome!

**Pull request merged**
